import { IndexString } from "./interfaces";

export const MAIN_TARGET_STABLE_COIN = 'DAI';
export const EXPECTED_AMOUNT = 52;

export const SELECTORS: IndexString = {
  BUY_SELL: '.iKhbZm',
  CONVERT_TAB: '[data-element-handle="folder-tab-convert"]',
  CURRENCY_LIST_FROM: '[data-element-handle="convert-from-selector"]',
  CURRENCY_LIST_TO: '[data-element-handle="convert-to-selector"]',
  CONVERT_PREVIEW_BUTTON: '[data-element-handle="convert-preview-button"]',
  CONVERT_CONFIRM_BUTTON: '[data-element-handle="convert-confirm-button"]',
  OVERLAY: '.hFwduY__overlay',
};

export const COINS_SELECTOR_PAIRS: IndexString = {
  AAVE: 'aave',
  ALGO: 'algorand',
  ATOM: 'cosmos',
  BAL: 'balancer',
  BAT: 'basic-attention-token',
  BAND: 'band-protocol',
  BCH: 'bitcoin-cash',
  BNT: 'bancor-network-token',
  BTC: 'bitcoin',
  CGLD: 'celo',
  COMP: 'compound',
  CVC: 'civic',
  DAI: 'dai',
  DASH: 'dash',
  DNT: 'district0x',
  EOS: 'eos',
  ETC: 'ethereum-classic',
  ETH: 'ethereum',
  FIL: 'filecoin',
  GRT: 'the-graph',
  KNC: 'kyber-network',
  LINK: 'chainlink',
  LRC: 'loopring',
  LTC: 'litecoin',
  MANA: 'decentraland',
  MKR: 'maker',
  NMR: 'numeraire',
  NU: 'nucypher',
  OMG: 'omg-network',
  OXT: 'orchid',
  REN: 'ren',
  REP: 'augur',
  SNX: 'synthetix-network-token',
  UMA: 'uma',
  UNI: 'uniswap',
  USDC: 'usdc',
  WBTC: 'wrapped-bitcoin',
  XLM: 'stellar',
  XTZ: 'tezos',
  YFI: 'yearn-finance',
  ZEC: 'zcash',
  ZRX: '0x',
};